# Generated by Django 5.1.7 on 2026-05-09 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('PASSPORT', 'Passport'), ('ID', 'ID Card'), ('LICENSE', 'Driver License')], max_length=20)),
                ('extracted_data', models.JSONField(default=dict)),
                ('redacted_image', models.ImageField(upload_to='redacted/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
