# Generated by Django 5.1.7 on 2026-03-02 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='online_status',
            field=models.CharField(choices=[('online', 'Online'), ('away', 'Away'), ('do_not_disturb', 'Do Not Disturb'), ('offline', 'Offline')], default='offline', max_length=20),
        ),
    ]
