# Generated by Django 5.1.7 on 2026-05-09 22:28

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_personaldocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentCluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('center', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('radius_m', models.FloatField(default=1000)),
                ('report_count', models.PositiveIntegerField(default=0)),
                ('unique_users', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None)),
                ('incident_ids', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('incident_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.incidenttype')),
            ],
        ),
        migrations.CreateModel(
            name='CrisisEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('triggered_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('incident_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crisis_events', to='accounts.incidenttype')),
                ('cluster', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='crisis_event', to='accounts.incidentcluster')),
            ],
            options={
                'ordering': ['-triggered_at'],
            },
        ),
        migrations.AddIndex(
            model_name='incidentcluster',
            index=models.Index(fields=['center'], name='accounts_in_center_2e8895_idx'),
        ),
    ]
