# Generated by Django 5.1.7 on 2026-05-10 04:32

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_crisis_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='crisisevent',
            name='mode',
            field=models.CharField(choices=[('local', 'Local'), ('global', 'Global')], default='local', max_length=10),
        ),
        migrations.AlterField(
            model_name='crisisevent',
            name='center',
            field=django.contrib.gis.db.models.fields.PointField(geography=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='crisisevent',
            name='cluster',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='crisis_event', to='accounts.incidentcluster'),
        ),
        migrations.AlterField(
            model_name='crisisevent',
            name='radius',
            field=models.FloatField(null=True),
        ),
    ]
