# Generated by Django 5.1.7 on 2026-05-10 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_crisisevent_mode_alter_crisisevent_center_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pulse',
            name='emergency_categories',
            field=models.CharField(blank=True, choices=[('medical_help', 'Medical Help'), ('water_needed', 'Water Needed'), ('shelter_needed', 'Shelter Needed'), ('sos', 'SOS'), ('fire', 'fire'), ('road_blocked', 'Road Blocked'), ('evacuation_info', 'Evacuation Info')], max_length=50),
        ),
    ]
