# Generated by Django 5.1.7 on 2026-05-10 00:27

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_incidentcluster_crisisevent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crisisevent',
            name='center',
            field=django.contrib.gis.db.models.fields.PointField(geography=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='crisisevent',
            name='radius',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='crisisevent',
            name='scope',
            field=models.CharField(choices=[('local', 'Local'), ('global', 'Global')], default='local', max_length=50),
        ),
    ]
