# Generated by Django 5.1.7 on 2026-03-02 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_conversation_message_follow_friendship'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='private_account',
            field=models.BooleanField(default=False),
        ),
    ]
