# Generated by Django 5.1.7 on 2026-05-10 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_crisisevent_center_crisisevent_radius_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crisisevent',
            name='scope',
        ),
    ]
