# Generated by Django 5.1.7 on 2026-03-02 19:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_private_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingFollow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_requests_sent', to=settings.AUTH_USER_MODEL)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_requests_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('requester', 'target')},
            },
        ),
    ]
