# Generated by Django 5.1.7 on 2026-05-10 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_crisisevent_scope'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='crisis_status',
            field=models.CharField(blank=True, choices=[('safe', "I'm Safe"), ('need_help', 'Need Help'), ('injured', 'Injured'), ('available_to_help', 'Available to Help')], default=None, max_length=30, null=True),
        ),
    ]
