# Generated by Django 5.1.7 on 2026-03-04 14:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_userobject_image_skill_image_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='skill',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='skill',
            name='user',
        ),
        migrations.RemoveField(
            model_name='skillimage',
            name='skill',
        ),
        migrations.RemoveField(
            model_name='userobject',
            name='owner',
        ),
        migrations.CreateModel(
            name='Pulse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, max_length=150)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('pulse_type', models.CharField(choices=[('servicii', 'Servicii / Evenimente'), ('obiecte', 'Obiecte / Produse')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('currencyType', models.CharField(default='RON', max_length=10)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pulses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PulseImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='pulse_images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('pulse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='accounts.pulse')),
            ],
        ),
        migrations.DeleteModel(
            name='ObjectImage',
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
        migrations.DeleteModel(
            name='SkillImage',
        ),
        migrations.DeleteModel(
            name='UserObject',
        ),
    ]
