# Generated by Django 5.1.7 on 2026-05-10 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_notification_crisis_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='crisisevent',
            name='mode',
            field=models.CharField(choices=[('local', 'Local'), ('global', 'Global')], default='local', max_length=10),
        ),
    ]
