# Generated by Django 5.1.7 on 2026-05-10 03:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_crisisevent_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crisisevent',
            name='cluster',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='crisis_event', to='accounts.incidentcluster'),
        ),
    ]
