# Generated by Django 5.1.7 on 2026-05-10 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_crisisevent_cluster'),
    ]

    operations = [
        migrations.AddField(
            model_name='pulse',
            name='emergency_categories',
            field=models.CharField(choices=[('medical_help', 'Medical Help'), ('water_needed', 'Water Needed'), ('shelter_needed', 'Shelter Needed'), ('sos', 'SOS'), ('fire', 'fire'), ('road_blocked', 'Road Blocked'), ('evacuation_info', 'Evacuation Info')], max_length=50, null=True),
        ),
    ]
